// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfitaxpwfewslewkvsxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5maXRheHB3ZmV3c2xld2t2c3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNDg5MzEsImV4cCI6MjA2OTcyNDkzMX0.hgnaEF8BTzvhRvuOA1RHFLRcQS_ijgV5ZU1yl_gT_AU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});